# Generated by Django 5.2.2 on 2025-06-11 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_exercise_options_exercise_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
