# Generated by Django 5.2.2 on 2025-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_exercise_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
