# Generated by Django 5.2.2 on 2025-06-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_exercise_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('-updated_at',)},
        ),
    ]
