# Generated by Django 5.2.2 on 2025-06-29 05:58

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('exercise', 'Category')
    Category.objects.bulk_create([
        Category(name='Weight training'),
        Category(name='Running'),
        Category(name='Cycling'),
        Category(name='Calisthenics'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_alter_exercise_updated_at'),
    ]

    operations = [
       migrations.RunPython(create_initial_categories),
    ]

